### PR TITLE
Add wikisource badges

### PR DESCRIPTION
**Pull request by filbertkm**
adds the svgs and pngs for the new badges, based on request in https://phabricator.wikimedia.org/T97014 and using exact colors from [ProofreadPage](https://www.mediawiki.org/wiki/Extension:Proofread_Page), along with css.

still needs to be added to WikimediaBadges.

nice to have in the future would be to only show wikisource badges in the badge selector for the wikisource section, etc., instead of list all badges everywhere.

### CODE REVIEW

**Comment by thiemowmde** [comment]
Meaning, CSS class name, color code:
* "Without text", `quality0`, `#DDD`.
* "Problematic", `quality2`, `#B0B0FF`.
* "Not proofread", `quality1`, `#FFA0A0`.
* "Proofread", `quality3`, `#FFE867`.
* "Validated", `quality4`, `#90FF90`.

Discrepancies:
* What's called "problematic" on Wikisource is called "incomplete" here. Intentional?

Sources:
* https://wikisource.org/wiki/Wikisource:ProofreadPage#Proofreading_path
* https://en.wikisource.org/wiki/Help:Page_status

**Comment by thiemowmde** [comment]
@filbertkm, I updated my review comment above. 1 relevant (the name) and 2 minor issues I would like to see fixed before merging this. Thanks.

**Comment by mariushoch** [comment]
> This patch also adds wb-badge.wb-badge-featuredtext, which is mentioned in T97014, but not here.

Where exactly should it be mentioned? I don't think I get the problem.

**Comment by thiemowmde** [comment]
In the commit message, but since it's now mentioned in my comment this is not critical.

**Comment by thiemowmde** [comment]
Uh, sorry to keep hitting this, but I found more issues:
* The PNGs are not transparent.
* @filbertkm used the customized silver badge as template. It has a wider base to make it easier to distinguish from `wb-badges-empty`. We should use `wb-badges-default` as a template.

I will fix both issues.

**Pull request merged**
